### ISSUE TITLE
not sure optimization is happening

### ISSUE THREAD

**Issue by bgmerrell** [google/autofdo#143]
Hi, I'm new to PGO so hopefully my issue / question makes sense.

I'm attempting to use optimize a HyperProtoBench benchmark binary using `create_llvm_prof`

Here's the versions of the things I'm using:
llvm 14.0.6
clang 14.0.0
autofdo master branch
perf 4.18.0
Linux 5.15

These are my steps:

1. Build HyperProtoBench benchmark with clang using llvm ld  (`clang++ -O3 -g -std=c++11 -fno-omit-frame-pointer -static -fcf-protection=return -fuse-ld=lld -Wl,-z,shstk -Wl,-z,cet-report=warning -Wl,--no-rosegment`)
2. `perf record -b --call-graph fp ./benchmark`
3. `./create_llvm_prof -binary=./benchmark -out=benchmark.prof`
4. Build a second HyperProtoBench benchmark binary, this time with `-fprofile-sample-use=benchmark.prof`

However, I don't think I'm seeing any performance improvement in the binaries. I'm also noticing the benchmark binary from step 1 and step 4 have the same sha256sum. Does that mean there were a problem? One weird thing I see is tens of thousands of these warnings during step 3: 

`[WARNING:../third_party/perf_data_converter/src/quipper/perf_serializer.cc:604] Ignoring branch stack entry reserved bits: 4`

I'll attach the` benchmark.prof` and `perf.data` files

[issue_artifacts.tar.gz](https://github.com/google/autofdo/files/9649421/issue_artifacts.tar.gz)

Thanks for any guidance!

**Comment by shenhanc78** [comment]
Thanks for reporting. The same sha256 checksum is definitely a red flag. I'll take a look.

**Comment by shenhanc78** [comment]
Hi Brian, I just noticed there is no "-fdebug-info-for-profiling" option used in either step 1 or step 4. This option is required in addition to "-g" or "-gmlt". Would you be able to retry with this option?

**Comment by bgmerrell** [comment]
Hi @shenhanc78, thanks for the info. I'm not working on the same project anymore, so I no longer have this environment and code. I'll assume this was my mistake and close this issue. Thanks again.
