### ISSUE TITLE
Linking errors when building tools for llvm

### ISSUE THREAD

**Issue by joshua-arch1** [google/autofdo#146]
When buidling aufdo tools for llvm, I have some linking errors:
 
```
CMakeFiles/quipper_perf.dir/perf_data.pb.cc.o: In function `quipper::PerfDataProto_PerfEventAttr::GetMetadata() const':
perf_data.pb.cc:(.text+0x3400): undefined reference to `google::protobuf::internal::AssignDescriptors(google::protobuf::internal::DescriptorTable const* (*)(), std::__1::once_flag*, google::protobuf::Metadata const&)'
```

Is that caused by protobuf? My protoc version is 3.20.3.

**Comment by shenhanc78** [comment]
Hi, the "AssignDescriptors" header is provided by "libprotobuf-dev" package, which on my system is 3.12.4-1.
And the implementation is provided by "libprotoc23" package  (the file: /usr/lib/x86_64-linux-gnu/libprotoc.so.23.0.4), which on my system is 3.12.4-1.

Can you check if your libprotobuf-dev and libprotoc23 packages have the exact same version numbers?

**Comment by joshua-arch1** [comment]
> Hi, the "AssignDescriptors" header is provided by "libprotobuf-dev" package, which on my system is 3.12.4-1. And the implementation is provided by "libprotoc23" package (the file: /usr/lib/x86_64-linux-gnu/libprotoc.so.23.0.4), which on my system is 3.12.4-1.
> 
> Can you check if your libprotobuf-dev and libprotoc23 packages have the exact same version numbers?

protoc --version
# libprotoc 3.20.3

As far as I am concerned, 3.20.3 is the version number of "libprotobuf-dev" package. What about "libprotoc23" package? I can only find /usr/lib/x86_64-linux-gnu/libprotobuf.so.10.0.0. How can I get the version number of "libprotoc23" package?

**Comment by shenhanc78** [comment]
Hi, could you get package versions for the following packages?
`apt list --installed libprotobuf-dev libprotoc23 protobuf-compiler`
All of them should have the same version.

The reason for the linking failure is that protoc (provided by the libprotoc23 and protobuf-compiler package) generates a function whose implementation has a version mismatch with the implementation contained in the libprotobuf-dev package.
