### ISSUE TITLE
create_gcov: Check failed: attr_size <= sizeof(perf_event_attr) (104 vs. 96)

### ISSUE THREAD

**Issue by ronin13** [google/autofdo#17]
create_gcov --binary= --profile=perf.data --gcov=perf.ado 

```
F0427 14:19:20.557157 22428 perf_reader.cc:1614] Check failed: attr_size <= sizeof(perf_event_attr) (104 vs. 96)
*** Check failure stack trace: ***
    @           0x4424f8  google::LogMessage::Flush()
    @           0x445459  google::LogMessageFatal::~LogMessageFatal()
    @           0x4317c0  quipper::PerfReader::ReadEventDescMetadata()
    @           0x432e93  quipper::PerfReader::ReadMetadata()
    @           0x4339b6  quipper::PerfReader::ReadFromPointer()
    @           0x433a9d  quipper::PerfReader::ReadFile()
    @           0x41d8c8  autofdo::PerfDataSampleReader::Append()
    @           0x41ced3  autofdo::SampleReader::ReadAndSetTotalCount()
    @           0x417451  autofdo::ProfileCreator::ReadSample()
    @           0x418572  autofdo::ProfileCreator::CreateProfile()
    @           0x4080c5  main
    @     0x7f6a3ce0e790  __libc_start_main
    @           0x4093e9  _start
    @              (nil)  (unknown)
```

This is on Linux 4.0 and gcc 5.1.0.

**Comment by danielcdh** [comment]
You will need to have Andi's patch applied if you run the tool for new
kernel (I'll merge these patches in once the patches go upstream).

https://gcc.gnu.org/ml/gcc/2015-04/msg00271.html

Dehao

**Comment by ronin13** [comment]
Thanks, I applied the patches onto autofdo head and it worked. 

I didn't need the version flags like here  '-gcov_version 1 -gcov loop.gcda -gcov_version 0x500e'

It worked without them, is that fine.

**Comment by ronin13** [comment]
I also see the issue described here https://www.mail-archive.com/gcc@gcc.gnu.org/msg76447.html

ie. I don't see any BR_INST_RETIRED:TAKEN or its variants in perf list.

Is autofdo-newer-perf patch from https://www.mail-archive.com/gcc@gcc.gnu.org/msg76454.html also required?

**Comment by danielcdh** [comment]
Yes

Dehao

**Comment by ronin13** [comment]
From what I see in the subsequent reply, first three patches in that are not required, but I tried to apply last three, but they are also failing with rejs.

Is using ocperf the other suitable way (or patches required on top of autofdo even for that?)

**Comment by danielcdh** [comment]
Sorry that I have not used ocperf myself. Could you reply to the original
gcc thread so that people with ocperf experience can help resolve the issue?

Dehao

**Comment by danielcdh** [comment]
I think this should have been fixed by https://github.com/google/autofdo/pull/65. Please re-open if otherwise.
