### ISSUE TITLE
addr2line_inlinestack.cc:250] Check failed: form == DW_FORM_ref4 

### ISSUE THREAD

**Issue by kula85** [google/autofdo#18]
I'm using clang version 3.5 LTO to compile spec2006 429.mcf. perf version 3.10.0-229.4.2.el7.  perf commandline used is "perf record -F 99 -q -a -g -- $command".  Did I do anything wrong? Or maybe the clang/llvm is old already? Thank you so much for the help.

**Comment by kula85** [comment]
Tried this with clang 3.5 and 3.6 with LTO. Both does not work. 
The thing is that dwarf4 only requires that  DW_AT_abstract_origin use "reference" value. Why is it here "DW_FORM_ref4" is enforced?

**Comment by kula85** [comment]
A pull request created.

**Comment by DavidCallahan** [comment]
I am seeing this problem as well. Did the pull request get generated? Is there another plan for this problem?

**Comment by kula85** [comment]
The fix is in the first pull request. Needs further confirmation of correctness though.

**Comment by danielcdh** [comment]
This should have been fixed now in master.
