### ISSUE TITLE
profile_merger: Check failed: count_threshold_ == 0

### ISSUE THREAD

**Issue by ilya-palachev** [google/autofdo#19]
Hi,

I'm trying to use binary profile_merger from your repository. I have collected  3 perf.data profiles for the same executable binary file that was run with 3 different input data. Then for each of them the create_gcov utility was run. Now I'm having 3 gcov data files after that and want to use them all during the compilation. How can it be done?
I have tried to use profile_merger mreger for that:

bash-4.3# /home/abuild/autofdo/build/profile_merger gcov.data.22760 gcov.data.22788 gcov.data.22815 --gcov_version=1
F0529 10:47:36.755566 31752 symbol_map.cc:193] Check failed: count_threshold_ == 0 (140733849599456 vs. 0) 
*** Check failure stack trace: ***
    @           0x449cad  google::LogMessage::Flush()
    @           0x44c6c9  google::LogMessageFatal::~LogMessageFatal()
    @           0x427f6e  autofdo::SymbolMap::CalculateThreshold()
    @           0x408ae9  main
    @     0x7f45ffbfea48  __libc_start_main
    @           0x409e89  _start
    @              (nil)  (unknown)
Aborted (core dumped)

Is it a bug or I'm doing something wrong?

Thanks...

**Comment by VictorRodriguez** [comment]
I am having the same issue :( . Any update ?

**Comment by ilya-palachev** [comment]
In my case I workarounded the problem just by removing that assertion.
But it would be better if maintainers show the proper way.

**Comment by danielcdh** [comment]
This error is not expected. Could you send me the afdo files that could
trigger this error in profile_merger?

Thanks,
Dehao

**Comment by VictorRodriguez** [comment]
HI @danielcdh  I have already send it to you. 

We are working on GCC Autofdo Tutorial , the code and documentation is at : 

https://github.com/VictorRodriguez/autofdo_tutorial

You can find there the code that we are using to test it. Your help and feedback is more than welcome

**Comment by danielcdh** [comment]
I've fixed the issue upstream. Please sync your client to master and let me
know if the problem is not fixed.

Thanks,
Dehao

**Comment by ilya-palachev** [comment]
With the mentioned fix the profile_merger works fine.
Dehao, thank you veru much!
