### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by gbriones1** [google/autofdo#26]
Can't compile, this message is displayed when running make:

In file included from chromiumos-wide-profiling/address_mapper.cc:5:0:
./chromiumos-wide-profiling/address_mapper.h:10:16: fatal error: list: No such file or directory
compilation terminated.
Makefile:770: recipe for target 'chromiumos-wide-profiling/address_mapper.o' failed
make: **\* [chromiumos-wide-profiling/address_mapper.o] Error 1

**Comment by danielcdh** [comment]
I think this should have been fixed by https://github.com/google/autofdo/pull/65, please re-open if otherwise.
