### ISSUE TITLE
Mention -g1 with -gmlt

### ISSUE THREAD

**Issue by brendangregg** [google/autofdo#29]
README has: "This means that you need to compile the binary with "-gmlt""

Did -gmlt become -g1 in newer gcc? README maybe should mention both (in case someone is on a -gmlt version).

**Comment by dnovillo** [comment]
On Fri, Nov 27, 2015 at 3:55 PM, Brendan Gregg <notifications@github.com>
wrote:

> README has: "This means that you need to compile the binary with "-gmlt""
>
> Did -gmlt become -g1 in newer gcc?
>

I don't know.  If it did, then using -g1 or -gmlt will produce the same
results.

Diego.

**Comment by danielcdh** [comment]
Updated README in https://github.com/google/autofdo/pull/48/commits/1408afb8c011b4198212fb3e16254d72fd462aa1
