### ISSUE TITLE
Compile error in llvm_profile_writer.cc

### ISSUE THREAD

**Issue by koukos** [google/autofdo#42]
Error details:

llvm_profile_writer.cc: In member function ‘virtual void autofdo::LLVMProfileBuilder::VisitTopSymbol(const string&, const autofdo::Symbol*)’:
llvm_profile_writer.cc:84:11: error: ‘class llvm::sampleprof::FunctionSamples’ has no member named ‘setName’
   profile.setName(name_ref);
           ^
llvm_profile_writer.cc: In member function ‘virtual void autofdo::LLVMProfileBuilder::VisitCallsite(const Callsite&)’:
llvm_profile_writer.cc:100:31: error: no matching function for call to ‘llvm::sampleprof::FunctionSamples::functionSamplesAt(llvm::sampleprof::LineLocation)’
           line, discriminator));
                               ^
llvm_profile_writer.cc:100:31: note: candidate is:
In file included from llvm_profile_writer.h:8:0,
                 from llvm_profile_writer.cc:30:
/usr/include/llvm/ProfileData/SampleProf.h:243:20: note: llvm::sampleprof::FunctionSamples& llvm::sampleprof::FunctionSamples::functionSamplesAt(const llvm::sampleprof::CallsiteLocation&)
   FunctionSamples &functionSamplesAt(const CallsiteLocation &Loc) {
                    ^
/usr/include/llvm/ProfileData/SampleProf.h:243:20: note:   no known conversion for argument 1 from ‘llvm::sampleprof::LineLocation’ to ‘const llvm::sampleprof::CallsiteLocation&’
Makefile:1065: recipe for target 'create_llvm_prof-llvm_profile_writer.o' failed
make[1]: *** [create_llvm_prof-llvm_profile_writer.o] Error 1
make[1]: Leaving directory '/home/koukos/Workspace/tools/autofdo'
Makefile:504: recipe for target 'all' failed
make: *** [all] Error 2

I could definitely fix it in the sourcecode; however, i am not entirely sure if it's indeed a bug or if it comes from a mis-configuration on my system. I am using gcc/g++ 4.8.5 on OpenSuse LEAP 42.2 system with linux kernel 4.4 (LTS) and libc 2.22. LLVM and clang version 3.8.0

Also confirmed on Ubuntu 16.04 LTS with similar compiler and kernel versions. LLVM 3.8, kernel 4.4, gcc 5.4, libc 2.23, ...

Before that i had some issues with autoconf/automake as mentioned in previous posts that i somehow worked around with: autoreconf -ivf

Any ideas?

Thanks in advance,
Konstantinos.

**Comment by koukos** [comment]
A quick fix on the problem is the following (not yet confirmed if it's working correctly):

File: llvm_profile_writer.cc

Line: 84
//  profile.setName(name_ref); // Comment out

Lines: 98-101
   auto &callee_profile =
       caller_profile.functionSamplesAt(llvm::sampleprof::LineLocation(
           line, discriminator));
   callee_profile.setName(GetNameRef(callsite.second));

// Replace them with the following lines, which use the definitions of LLVM 3.8

  auto &callee_profile =
      caller_profile.functionSamplesAt(llvm::sampleprof::CallsiteLocation(
          line, discriminator,GetNameRef(callsite.second)));

**Comment by danielcdh** [comment]
Should have been fixed in master now.
