### ISSUE TITLE
create_gcov crash 

### ISSUE THREAD

**Issue by superlupo** [google/autofdo#46]
Could anyone help to decode this error message when I attempt to run  create_gcov

$create_gcov  --binary=`which athena.py` --profile=./perf.data --gcov=basic.gcov -gcov_version=1 
E0721 13:56:07.792387 23417 address_mapper.cc:154] Could not find space to map addr=7f8c5b8dc000 with size a000
F0721 13:56:07.793525 23417 perf_parser.cc:151] Check failed: MapMmapEvent(&event.mmap2, i) Unable to map MMAP2 event!
*** Check failure stack trace: ***
    @           0x441224  google::LogMessage::Flush()
    @           0x443fd9  google::LogMessageFatal::~LogMessageFatal()
    @           0x43a4af  quipper::PerfParser::ProcessEvents()
    @           0x43aaf4  quipper::PerfParser::ParseRawEvents()
    @           0x41c590  autofdo::PerfDataSampleReader::Append()
    @           0x41baf3  autofdo::SampleReader::ReadAndSetTotalCount()
    @           0x414ef8  autofdo::ProfileCreator::ReadSample()
    @           0x415cf2  autofdo::ProfileCreator::CreateProfile()
    @           0x40816e  main
    @     0x7f8464db3b35  __libc_start_main
    @           0x4095d2  (unknown)
    @              (nil)  (unknown)
Aborted (core dumped)

**Comment by danielcdh** [comment]
I just rebased the symbolizer. For this one, the fix should have been upstreamed in https://chromium.googlesource.com/chromiumos/platform2/+/master/chromiumos-wide-profiling/

I spent some time trying to rebase perf_reader/perf_parser, but there are too much change, and we do not want to pull the entire protobuf processing logic in. Thus may need more effort to rebase. I am quite occupied at this time and thus will put his task on hold for a while. During the mean time, feel free to send pull request if you are able to help rebase the perf reader/parser.

Cheers,
Dehao

**Comment by superlupo** [comment]
Thanks Dehao for the esponse. Unfortunately I'm not able to help with the rebase. Do you have time estimate for when the rebase could be completed?

**Comment by AnantSah** [comment]
I am facing the same issue while using sample_merger.
Any estimate on when this will be fixed ?

**Comment by AnantSah** [comment]
I am able to resolve the issue by replacing 2 files - 

autofdo-master2/chromiumos-wide-profiling/address_mapper.h
autofdo-master2/chromiumos-wide-profiling/address_mapper.cc

from original to one provided in the link - 

https://chromium.googlesource.com/chromiumos/platform2/+/factory-gru-8652.B/chromiumos-wide-profiling/

**Comment by danielcdh** [comment]
I assume this is fixed. Please re-open if otherwise.
