### ISSUE TITLE
incorrect assumption that branch record will set either predicted or mispred

### ISSUE THREAD

**Issue by algr** [google/autofdo#56]
In perf-parser.cc:
```
    // Either predicted or mispredicted, not both. But don't use a CHECK here,
    // just exit gracefully because it's a minor issue.
    if (entry.flags.predicted == entry.flags.mispred) {
      LOG(ERROR) << "Branch stack entry predicted and mispred flags "
                 << "both have value " << entry.flags.mispred;
      return false;
    }
```
It is valid for neither flag to be set, when we don't know if the branch was predicted. This is the case when decoding Intel PT.

perf has had a workaround for this for some time (by means of a non default command-line option): https://patchwork.kernel.org/patch/7264751/

But it would be cleaner to fix it in AutoFDO.

**Comment by danielcdh** [comment]
I think this should have been fixed by https://github.com/google/autofdo/pull/65, pease re-open if otherwise.
