### ISSUE TITLE
Cannot read compilation info from binary under GCC 7.3

### ISSUE THREAD

**Issue by longdafeng** [google/autofdo#66]
Thanks firstly, any help are appreciated.

When I used GCC 7.3 to build mysql, I found this warning 

"W0412 18:42:05.956995 92904 module_grouper.cc:60] Cannot read compilation info from binary. Please use -frecord-compilation-info-in-elf when building the binary"

At the same time, create_gcov failed to convert perf.data to gcov. The gcov file is empty.

what's more, I can't find "-frecord-compilation-info-in-elf" in GCC 7.3 manual, I google it and it seems the compile flag can only be used by Google-gcc.

How to resolve the problem?

BTW: But I successfully convert the perf.data to gcov of the sort.c example under GCC 7.3 (https://gcc.gnu.org/wiki/AutoFDO/Tutorial)

**Comment by longdafeng** [comment]
create_gcov works when I set LD_LIBRARY_PATH include the GCC library's path

**Comment by huuidy** [comment]
> create_gcov works when I set LD_LIBRARY_PATH include the GCC library's path

what is the meaning? the compile flag can only be used by Google-gcc, so setting LD_LIBRARY_PATH is useful?

**Comment by dannieking66** [comment]
> create_gcov works when I set LD_LIBRARY_PATH include the GCC library's path

Could you explain  in detail? How to set LD_LIBRARY_PATH?
