### ISSUE TITLE
Assert when unsupported event type under kernel 4.9

### ISSUE THREAD

**Issue by longdafeng** [google/autofdo#67]
When linux kernel  is 4.9.79, there are several unsupported event type in the perf.data.

it will assert. 

May we could skip these events.

**Comment by longdafeng** [comment]
https://github.com/google/autofdo/pull/68

**Comment by danielcdh** [comment]
Please sync to head and retry. I expect https://github.com/google/autofdo/pull/65 to have fixed this.
