### ISSUE TITLE
create_gcov report "No buildid found in binary"

### ISSUE THREAD

**Issue by ktap** [google/autofdo#7]
Hi,

The create_gcov always report cannot found binary buildid, but my kernel
already compiled with buildid.

[root@localhost autofdo]# ./create_gcov --binary=../linux/vmlinux --profile=../linux/perf.data --gcov=1
E0512 10:06:07.650653 14367 elf_reader.cc:789] Malformed .note.gnu.build-id section.
E0512 10:06:07.657847 14367 sample_reader.cc:233] No buildid found in binary
[root@localhost autofdo]#
[root@localhost autofdo]#
[root@localhost autofdo]# readelf -n ../linux/vmlinux|grep build
  GNU                  0x00000014       NT_GNU_BUILD_ID (unique build ID bitstring)

**Comment by danielcdh** [comment]
This should have been fixed by https://github.com/google/autofdo/commit/d6834df515bb47f14e8fbc9538d7350f73ee5c00
